name: build

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ktlint lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Execute lint check
        run: ./gradlew ktlintCheck --no-configuration-cache
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Execute unit tests
        run: ./gradlew jvmTest # jvmTest + testUnitTest = allTest (so execute separately)
  ui-unit-test:
    name: Ui unit test on android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ weather ]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Execute ui tests for ${{ matrix.app }}
        run: ./gradlew :${{ matrix.app }}:app:testStagingDebugUnitTest
  screenshot-test:
    name: Screenshot test on android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ weather ]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: 'true'
          submodules: 'recursive'
          ssh-key: ${{ secrets.git_ssh_key }}
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Execute snapshot tests for ${{ matrix.app }}
        run: ./gradlew :${{ matrix.app }}:app:verifyRoborazziStagingDebug
  test-kover:
    name: Report coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ weather ]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Execute kover report on tests for ${{ matrix.app }}
        run: ./gradlew :${{ matrix.app }}:app:koverXmlReportCustom
      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/${{ matrix.app }}/app/build/reports/kover/reportCustom.xml
          title: ${{ matrix.app }} Code Coverage
          update-comment: true
          min-coverage-overall: 50
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
  build-android-app:
    name: Build android application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ weather, todo ]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.app }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.app }}
      - name: Execute build ${{ matrix.app }} android app
        run: ./gradlew :${{ matrix.app }}:app:bundleStagingDebug -Pbuildkonfig.flavor=staging

