name: build

on:
  on:
    pull_request:
    workflow_dispatch:
      pull_request:
        branches:
          - master
          - feature/*
          - fix/*

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

jobs:
  lint:
    name: Kotlin lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradlew execute permission
        run: chmod +x gradlew
      - name: Lint run
        run: ./gradlew check
  ui-unit-test:
    name: Ui unit test on android
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradlew execute permission
        run: chmod +x gradlew
      - name: Execute ui tests
        run: ./gradlew testStagingDebugUnitTest
  build-android-app:
    name: Build android application
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradlew execute permission
        run: chmod +x gradlew
      - name: Execute build android app
        run: ./gradlew :weather:app:bundleStagingDebug :todo:app:bundleStagingDebug -Pbuildkonfig.flavor=staging

